apiVersion: v1
kind: Service
metadata:
  name: sisal-svc
  namespace: snisid-core
  labels:
    app: sisal-svc
spec:
  type: ClusterIP
  ports:
  - port: 8128
    targetPort: 8128
    protocol: TCP
    name: http
  selector:
    app: sisal-svc