BEGIN;

CREATE TYPE siar_weapon_type AS ENUM (
    'HANDGUN','RIFLE','SHOTGUN','SUBMACHINE_GUN','ASSAULT_RIFLE',
    'MACHINE_GUN','SNIPER','RPG','GRENADE','HOMEMADE','OTHER'
);

CREATE TYPE siar_status AS ENUM (
    'REGISTERED','REPORTED_STOLEN','SEIZED','DESTROYED',
    'REPORTED_LOST','TRANSFERRED','DEACTIVATED'
);

CREATE TYPE siar_registration_type AS ENUM (
    'CIVILIAN','POLICE','MILITARY','SECURITY_COMPANY',
    'EMBASSY','ILLEGAL_FOUND','HISTORICAL'
);

CREATE TYPE siar_license_type AS ENUM (
    'CARRY','POSSESS','DEALER','COLLECTOR','IMPORT','EXPORT'
);

CREATE TYPE siar_transfer_type AS ENUM (
    'SALE','GIFT','INHERITANCE','CONFISCATION','RETURN','THEFT_REPORTED'
);

CREATE TYPE siar_dealer_status AS ENUM (
    'ACTIVE','SUSPENDED','REVOKED','EXPIRED'
);

COMMIT;
