apiVersion: v1
kind: Service
metadata:
  name: ucref-svc
  namespace: snisid-core
  labels:
    app: ucref-svc
spec:
  type: ClusterIP
  ports:
  - port: 8112
    targetPort: 8112
    protocol: TCP
    name: http
  selector:
    app: ucref-svc