BEGIN;

CREATE TYPE sifr_crossing_direction AS ENUM ('ENTRY', 'EXIT');
CREATE TYPE sifr_doc_type AS ENUM (
    'PASSPORT', 'NATIONAL_ID', 'LAISSEZ_PASSER',
    'BIRTH_CERTIFICATE', 'TRAVEL_DOCUMENT', 'NONE'
);
CREATE TYPE sifr_alert_type AS ENUM (
    'WANTED_PERSON', 'STOLEN_DOCUMENT', 'BLACKLIST',
    'ACTIVE_WARRANT', 'SANCTIONS', 'CUSTOMS_ALERT'
);

COMMIT;
