{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: sniside
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: sniside-api-auth
  namespace: sniside
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sniside
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
      to:
        - operation:
            methods: ["POST", "GET"]
            paths: ["/intelligence/v1/*"]
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sniside-ingress
  namespace: istio-system
spec:
  hosts:
    - "api.sniside.ht"
    - "*.sniside.ht"
  gateways:
    - sniside-gateway
  http:
    - match:
        - uri:
            prefix: /intelligence/v1/
      route:
        - destination:
            host: sniside-kong.sniside.svc.cluster.local
            port:
              number: 8080
      corsPolicy:
        allowOrigins:
          - exact: https://*.sniside.ht
        allowMethods: ["GET", "POST", "PUT", "DELETE"]
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sniside-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: sniside-tls
      hosts:
        - "*.sniside.ht"
{{- end }}
