BEGIN;

CREATE TYPE trafar_route_type AS ENUM (
    'MARITIME_DIRECT','MARITIME_VIA_BAHAMAS',
    'AIR_CARGO','AIR_PASSENGER',
    'LAND_BORDER_DOM','LAND_BORDER_OTHER',
    'POSTAL','MIXED'
);

CREATE TYPE trafar_method AS ENUM (
    'STRAW_PURCHASE','STOLEN_DIVERTED','CORRUPT_OFFICIAL',
    'FALSE_END_USER','DARK_WEB','DIPLOMATIC_POUCH',
    'CONCEALED_CARGO','DRUGS_FOR_GUNS_SWAP','UNKNOWN'
);

COMMIT;
