apiVersion: v1
kind: Service
metadata:
  name: bio-surveillance-ht
  namespace: snisid-national-security
  labels:
    app: bio-surveillance-ht
spec:
  type: ClusterIP
  ports:
  - port: 8305
    targetPort: 8305
    protocol: TCP
    name: http
  selector:
    app: bio-surveillance-ht
