BEGIN;

CREATE TYPE afis_finger_position AS ENUM (
    'RIGHT_THUMB','RIGHT_INDEX','RIGHT_MIDDLE','RIGHT_RING','RIGHT_LITTLE',
    'LEFT_THUMB','LEFT_INDEX','LEFT_MIDDLE','LEFT_RING','LEFT_LITTLE',
    'RIGHT_PALM','LEFT_PALM','UNKNOWN'
);

CREATE TYPE afis_capture_method AS ENUM (
    'LIVESCANNER','INKROLL','LATENT_LIFT','PHOTO','UNKNOWN'
);

CREATE TYPE afis_subject_type AS ENUM (
    'SUSPECT','CRIMINAL','VICTIM','UNKNOWN_DECEASED','MISSING_PERSON','EMPLOYEE'
);

COMMIT;
