apiVersion: v1
kind: Service
metadata:
  name: service-desk-svc
  namespace: snisid-core
  labels:
    app: service-desk-svc
spec:
  type: ClusterIP
  ports:
  - port: 8102
    targetPort: 8102
    protocol: TCP
    name: http
  selector:
    app: service-desk-svc
