# SNISID National Governance Framework
## Sovereign Administrative & Legal Policy Blueprint

This document defines the overarching **National Governance Framework** for the Système National d’Identification et d’Interopérabilité Sécurisée des Identités et des Données (SNISID). It establishes the rules, policies, and legal boundaries required to operate a sovereign, Zero Trust identity ecosystem for the Republic of Haiti.

---

## 1. Legal Governance
The foundation of SNISID relies on robust national legislation that legitimizes digital transactions.
- **Digital Identity Decree:** A legal framework recognizing the SNISID eID as legally equivalent to physical national identity cards (CIN).
- **Electronic Signatures Law:** Legally binds citizens and civil servants to cryptographic signatures generated by SNISID-issued PKI certificates, rendering them admissible in Haitian courts.
- **National Interoperability Mandate:** Legally compels critical government agencies (DGI, Customs, Immigration) to utilize SNISID for cross-agency data verification, phasing out legacy paper-based checks.

## 2. Data Governance
- **Data Sovereignty & Residency:** All SNISID data (Citizen Registry, Biometric Templates, Audit Logs) must physically reside within the borders of the Republic of Haiti. Cloud backups must utilize sovereign, government-controlled infrastructure.
- **Data Classification:** Strict taxonomy for data. (e.g., *Level 4: Top Secret* for Biometric Templates; *Level 1: Public* for Agency API endpoints).
- **Data Ownership:** The State holds custody of the infrastructure, but the *Citizen* is recognized as the ultimate owner of their demographic data.

## 3. Cybersecurity Governance
- **National CISO Authority:** The Chief Information Security Officer of SNISID holds veto power over any architecture change that degrades the Zero Trust or cryptographic posture of the system.
- **Continuous Compliance:** Strict adherence to ISO/IEC 27001 (Information Security Management) and NIST Cybersecurity Framework (CSF).
- **Mandatory Reporting:** Any suspected data breach or APT (Advanced Persistent Threat) intrusion must be legally reported to the National Security Council within 4 hours.

## 4. Identity Governance
- **Identity Lifecycle Management:** Clear policies for the creation, suspension, and revocation of digital identities. E.g., Upon issuance of a legal death certificate by the civil registry, the SNISID identity is automatically transitioning to a "Deceased/Archived" state, instantly invalidating all associated PKI certificates.
- **Role-Based Access:** Government employee identities are tightly coupled to their HR status. Termination automatically severs IAM access globally.

## 5. Privacy Governance
- **Data Minimization:** APIs return only the *absolute minimum* data required for a transaction. (e.g., A bar verifying age receives a Boolean `is_over_18 = true`, not the citizen's actual date of birth).
- **Right to Erasure & Rectification:** Processes for citizens to legally contest and correct erroneous data in the master registry.
- **Algorithmic Transparency:** The algorithms used for biometric 1:N deduplication must be periodically reviewed for racial or demographic bias by an independent board.

## 6. PKI Governance
- **Certificate Policy (CP):** Defines the legal and policy requirements for what the PKI certificates are used for (e.g., Citizen Authentication vs. Government Document Signing).
- **Certification Practice Statement (CPS):** A highly detailed, public-facing document describing the exact operational procedures (Key Ceremonies, HSM dual-control, physical bunker security) used by the SNISID Root CA.
- **Key Ceremony Audits:** Root CA key generation ceremonies must be physically attended and signed off by independent third-party auditors and government officials.

## 7. Inter-Agency Governance
- **Memorandums of Understanding (MOUs):** Formal agreements dictating the terms under which Agency A (e.g., Health) can query Agency B (e.g., Justice).
- **SLA Enforcement:** Agencies acting as Service Providers on the X-Road API Gateway must adhere to 99.9% uptime.
- **Decentralization Principle:** SNISID does not create a massive centralized database of all citizen interactions. SNISID routes the request; the data remains at the source agency.

## 8. Audit Governance
- **WORM Immutability:** All administrative actions (e.g., "Admin X viewed Citizen Y's record") are written to Write-Once-Read-Many (WORM) storage.
- **Independent Oversight:** An independent Inspector General (IG) is granted read-only access to the SIEM and Audit Ledgers to hunt for internal government corruption or unauthorized mass-surveillance.
- **Cryptographic Non-Repudiation:** Because all API requests are signed via mTLS and JWTs, a malicious actor cannot deny having made a specific data request.

## 9. Citizen Consent Governance
- **Explicit Consent Architecture:** Third-party entities (Banks, Telecoms) cannot query SNISID for a citizen's data without explicit, real-time cryptographic consent from the citizen.
- **Push Notification Verification:** Consent requests trigger a push notification to the citizen's SNISID Mobile App. The citizen must biometric-authenticate to approve the data release.
- **Revocation of Consent:** Citizens possess a centralized dashboard to view all active consent grants and can revoke them with a single click, immediately blocking future API access for that third-party.

---

## 🏛️ Organes de Gouvernance — 5 Instances (v2.0)

| Organe | Membres | Pouvoir |
|---|---|---|
| **COMITÉ DE PILOTAGE NATIONAL** | Ministre + CISO + DG ONI — Réunion Mensuelle | Décisions stratégiques, gouvernance budgétaire, validation des jalons GO/NO-GO de transition de phase |
| **CONSEIL TECHNIQUE SNISID** | Architectes système + experts cybersécurité — Réunion Bimensuelle | Arbitrage des choix d'architecture, définition des standards de chiffrement et conformité NIST/FIPS |
| **COMMISSION ÉTHIQUE BIOMÉTRIQUE** | Représentants société civile + juristes indépendants — Réunion Trimestrielle | Audit et validation de l'usage des templates biométriques, contrôle de non-biais |
| **CHANGE CONTROL BOARD (CCB)** | Architectes + SRE Lead + Security Officer — Réunion Hebdomadaire minimum | Approbation obligatoire de toute modification d'infrastructure ou de configuration Kubernetes |
| **COMITÉ INTERMINISTÉRIEL X-ROAD** | Représentants des agences connectées (DGI, ONI, etc.) — Réunion Mensuelle | Coordination des intégrations de l'interopérabilité nationale et de l'annuaire d'API X-Road |

---

## ⚖️ Cadre Légal Requis & Suivi Réglementaire (v2.0)

Pour maintenir la souveraineté numérique et la légalité républicaine, le calendrier juridique impose la validation des jalons suivants :

* **[ ] Loi sur la protection des données biométriques :** *Obligatoire avant le démarrage de la Phase 2.* Encadre l'extraction des templates mathématiques et interdit le stockage d'images brutes.
* **[ ] Cadre légal du NNI (Numéro National d'Identification) :** *Obligatoire avant le démarrage de la Phase 2.* Légitime l'attribution et l'utilisation du NNI comme clé d'interopérabilité unique.
* **[ ] Réglementation de l'accès inter-agences (X-Road légal) :** *Obligatoire avant le démarrage de la Phase 3.* Définit les droits d'accès aux APIs entre ministères et institue le principe de non-centralisation.
* **[ ] Loi sur la cybersécurité nationale :** *Obligatoire avant le démarrage de la Phase 4.* Fixe les obligations de rapport de brèche sous 4h et légitime l'autorité de veto du CISO.
* **[ ] Accord international de la diaspora (site DR offshore) :** *Obligatoire avant le démarrage de la Phase 5.* Accord bilatéral sécurisant le stockage air-gappé des sauvegardes de la base nationale de secours en dehors du territoire.

---
*Ratifié par le Comité de Pilotage National du SNISID.*
