BEGIN;

CREATE TYPE biar_recovery_context AS ENUM (
    'POLICE_OPERATION','CHECKPOINT','PORT_SEIZURE','AIRPORT_SEIZURE',
    'COMMUNITY_SURRENDER','CRIME_SCENE','RAID','BORDER_SEIZURE','OTHER'
);

CREATE TYPE biar_weapon_disposition AS ENUM (
    'HELD_AS_EVIDENCE','DESTROYED','RETURNED_TO_OWNER',
    'TRANSFERRED_TO_POLICE','SENT_TO_INTERPOL','PENDING'
);

COMMIT;
