---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: snisid-core
# Zero Trust: Do not automatically mount the API token unless explicitly needed
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: snisid-core
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: snisid-data
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: snisid-security
automountServiceAccountToken: true # Vault often needs it for k8s auth method
