BEGIN;

CREATE TYPE gang_structure_type AS ENUM (
    'HIERARCHY','NETWORK','CELL','COALITION','FRANCHISE'
);

CREATE TYPE gang_activity_level AS ENUM (
    'DORMANT','LOW','MODERATE','HIGH','EXTREME'
);

CREATE TYPE gang_primary_activity AS ENUM (
    'KIDNAPPING','DRUG_TRAFFICKING','ARMS_TRAFFICKING',
    'EXTORTION','TERRITORY_CONTROL','CONTRACT_KILLING',
    'HUMAN_TRAFFICKING','MONEY_LAUNDERING','MIXED'
);

COMMIT;
