apiVersion: v1
kind: Service
metadata:
  name: dpide-svc
  namespace: snisid-core
  labels:
    app: dpide-svc
spec:
  type: ClusterIP
  ports:
  - port: 8121
    targetPort: 8121
    protocol: TCP
    name: http
  selector:
    app: dpide-svc