apiVersion: v1
kind: Service
metadata:
  name: sifr-svc
  namespace: snisid-core
  labels:
    app: sifr-svc
spec:
  type: ClusterIP
  ports:
  - port: 8106
    targetPort: 8106
    protocol: TCP
    name: http
  selector:
    app: sifr-svc