BEGIN;

CREATE TYPE sltd_doc_type AS ENUM (
    'PASSPORT','NATIONAL_ID','TRAVEL_DOCUMENT',
    'VISA','RESIDENCE_PERMIT','REFUGEE_DOCUMENT','LAISSEZ_PASSER'
);

CREATE TYPE sltd_doc_status AS ENUM (
    'LOST','STOLEN','REVOKED','EXPIRED','FOUND','RECOVERED','CANCELLED'
);

COMMIT;
