apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: backend-network-delay
  namespace: snisid-staging
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: snisid-backend
  delay:
    latency: '200ms'
    correlation: '100'
    jitter: '0ms'
  duration: '1m'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: backend-pod-kill
  namespace: snisid-staging
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: snisid-backend
  duration: '2m'
  scheduler:
    cron: '@every 5m'
