BEGIN;

CREATE TYPE chef_role_type AS ENUM (
    'SUPREME_LEADER','ZONE_COMMANDER','LIEUTENANT',
    'SOLDIER','ASSOCIATE','FINANCIER','ENABLER','INFORMANT'
);

CREATE TYPE chef_status AS ENUM (
    'ACTIVE','ARRESTED','DETAINED','DECEASED','FLED_COUNTRY','UNKNOWN'
);

COMMIT;
