package domain

import (
	"time"

	"github.com/google/uuid"
)

type BehavioralAlert struct {
	AlertID          uuid.UUID  `json:"alert_id"`
	OfficerSnisidID  uuid.UUID  `json:"officer_snisid_id"`
	AlertType        string     `json:"alert_type"`
	Description      string     `json:"description"`
	ModuleSource     string     `json:"module_source,omitempty"`
	RiskScore        int16      `json:"risk_score"`
	AutoGenerated    bool       `json:"auto_generated"`
	Reviewed         bool       `json:"reviewed"`
	ReviewedBy       *uuid.UUID `json:"reviewed_by,omitempty"`
	IsFalsePositive  bool       `json:"is_false_positive"`
	CorrCaseID       *uuid.UUID `json:"corr_case_id,omitempty"`
	CreatedAt        time.Time  `json:"created_at"`
}

type AssetDeclaration struct {
	DeclarationID         uuid.UUID `json:"declaration_id"`
	OfficerSnisidID       uuid.UUID `json:"officer_snisid_id"`
	DeclarationYear       int16     `json:"declaration_year"`
	RealEstateUSD         float64   `json:"real_estate_usd"`
	VehiclesUSD           float64   `json:"vehicles_usd"`
	BankAccountsUSD       float64   `json:"bank_accounts_usd"`
	OtherAssetsUSD        float64   `json:"other_assets_usd"`
	TotalAssetsUSD        float64   `json:"total_assets_usd"`
	KnownSalaryAnnualUSD  float64   `json:"known_salary_annual_usd,omitempty"`
	UnexplainedWealthUSD  float64   `json:"unexplained_wealth_usd,omitempty"`
	IsFlagged             bool      `json:"is_flagged"`
	VerifiedBy            *uuid.UUID `json:"verified_by,omitempty"`
	CreatedAt             time.Time `json:"created_at"`
}

type CreateDeclarationRequest struct {
	OfficerSnisidID      uuid.UUID `json:"officer_snisid_id" validate:"required"`
	DeclarationYear      int16     `json:"declaration_year" validate:"required"`
	RealEstateUSD        float64   `json:"real_estate_usd"`
	VehiclesUSD          float64   `json:"vehicles_usd"`
	BankAccountsUSD      float64   `json:"bank_accounts_usd"`
	OtherAssetsUSD       float64   `json:"other_assets_usd"`
	KnownSalaryAnnualUSD float64   `json:"known_salary_annual_usd"`
}

type RiskScore struct {
	OfficerSnisidID uuid.UUID `json:"officer_snisid_id"`
	TotalAlerts     int       `json:"total_alerts"`
	MaxRiskScore    int16     `json:"max_risk_score"`
	AvgRiskScore    float64   `json:"avg_risk_score"`
	OpenCases       int       `json:"open_cases"`
	OverallRisk     string    `json:"overall_risk"`
}
