apiVersion: v1
kind: Service
metadata:
  name: sigint-ht
  namespace: snisid-national-security
  labels:
    app: sigint-ht
spec:
  type: ClusterIP
  ports:
  - port: 8301
    targetPort: 8301
    protocol: TCP
    name: http
  selector:
    app: sigint-ht
