BEGIN;

CREATE TYPE expl_type AS ENUM (
    'IED','GRENADE','RPG','MORTAR','LANDMINE','DYNAMITE',
    'BLASTING_CAP','AMMUNITION_BULK','MILITARY_ORDNANCE','UNKNOWN'
);

CREATE TYPE expl_status AS ENUM (
    'RECOVERED','DESTROYED','DETONATED','STORED_EVIDENCE','TRANSFERRED'
);

CREATE TYPE expl_incident_type AS ENUM (
    'FIND','DETONATION','SEIZURE','SURRENDER'
);

COMMIT;
