replicaCount: 3

image:
  repository: registry.snisid.gov/snisid-backend
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: false
  name: "backend-sa"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  VAULT_ADDR: "https://vault.snisid-security.svc.cluster.local:8200"
