apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-service
  namespace: argocd
spec:
  project: snisid-core
  source:
    repoURL: 'https://github.com/snisid/identity-service.git'
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: snisid-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
