[INPUT]
    Name              tail
    Path              /var/log/keycloak/audit.log
    Parser            json
    Tag               keycloak.audit

[FILTER]
    Name              modify
    Match             keycloak.audit
    # Enrich the log for the SOC
    Add               system snisid_iam
    Add               log_type authentication

[OUTPUT]
    Name              kafka
    Match             keycloak.audit
    Brokers           kafka-broker.snisid-core.svc.cluster.local:9092
    Topics            snisid.audit.events
    Format            json
    # TLS Configuration for Kafka
    tls               On
    tls.ca_file       /etc/fluent-bit/certs/ca.crt
