apiVersion: v1
kind: Service
metadata:
  name: infra-ht
  namespace: snisid-core
  labels:
    app: infra-ht
spec:
  type: ClusterIP
  ports:
  - port: 8209
    targetPort: 8209
    protocol: TCP
    name: http
  selector:
    app: infra-ht
