package service

import (
	"context"
	"math"
	"time"

	"github.com/google/uuid"
	"github.com/snisid/platform/services/corr/internal/domain"
	"github.com/snisid/platform/services/corr/internal/repository"
)

type AlertService struct {
	alertRepo repository.AlertRepository
	declRepo  repository.DeclarationRepository
	caseRepo  repository.CaseRepository
}

func NewAlertService(alertRepo repository.AlertRepository, declRepo repository.DeclarationRepository, caseRepo repository.CaseRepository) *AlertService {
	return &AlertService{alertRepo: alertRepo, declRepo: declRepo, caseRepo: caseRepo}
}

func (s *AlertService) ListAlerts(ctx context.Context) ([]*domain.BehavioralAlert, error) {
	return s.alertRepo.List(ctx)
}

func (s *AlertService) CreateDeclaration(ctx context.Context, d *domain.AssetDeclaration) error {
	return s.declRepo.Create(ctx, d)
}

func (s *AlertService) ListFlaggedDeclarations(ctx context.Context) ([]*domain.AssetDeclaration, error) {
	return s.declRepo.ListFlagged(ctx)
}

func (s *AlertService) ListRiskScores(ctx context.Context) ([]*domain.RiskScore, error) {
	alerts, err := s.alertRepo.List(ctx)
	if err != nil {
		return nil, err
	}
	cases, err := s.caseRepo.List(ctx)
	if err != nil {
		return nil, err
	}

	alertMap := make(map[uuid.UUID][]*domain.BehavioralAlert)
	for _, a := range alerts {
		alertMap[a.OfficerSnisidID] = append(alertMap[a.OfficerSnisidID], a)
	}

	caseMap := make(map[uuid.UUID]int)
	for _, c := range cases {
		if c.Status == domain.StatusReported || c.Status == domain.StatusUnderInvestigation {
			caseMap[c.OfficerSnisidID]++
		}
	}

	var scores []*domain.RiskScore
	for oid, officerAlerts := range alertMap {
		var total int16
		var maxScore int16
		for _, a := range officerAlerts {
			total += a.RiskScore
			if a.RiskScore > maxScore {
				maxScore = a.RiskScore
			}
		}
		avg := float64(total) / float64(len(officerAlerts))
		avg = math.Round(avg*100) / 100
		overall := "LOW"
		if avg >= 80 {
			overall = "CRITICAL"
		} else if avg >= 60 {
			overall = "HIGH"
		} else if avg >= 40 {
			overall = "MEDIUM"
		}
		scores = append(scores, &domain.RiskScore{
			OfficerSnisidID: oid,
			TotalAlerts:     len(officerAlerts),
			MaxRiskScore:    maxScore,
			AvgRiskScore:    avg,
			OpenCases:       caseMap[oid],
			OverallRisk:     overall,
		})
	}
	return scores, nil
}

type AuditEvent struct {
	OfficerID      uuid.UUID
	RecordCount    int
	Duration       time.Duration
	Timestamp      time.Time
	Action         string
	Module         string
	Classification string
	IsAuthorized   bool
}

type EventPublisher interface {
	Publish(ctx context.Context, topic string, event interface{}) error
}

type IGPNHNotifier interface {
	NotifyUrgent(ctx context.Context, alert domain.BehavioralAlert) error
}

type BehavioralAnalyzer struct {
	alertRepo repository.AlertRepository
	kafka   EventPublisher
	igpnh   IGPNHNotifier
}

func NewBehavioralAnalyzer(alertRepo repository.AlertRepository, kafka EventPublisher, igpnh IGPNHNotifier) *BehavioralAnalyzer {
	return &BehavioralAnalyzer{alertRepo: alertRepo, kafka: kafka, igpnh: igpnh}
}

func (s *BehavioralAnalyzer) AnalyzeAuditEvent(ctx context.Context, event AuditEvent) error {
	alerts := []domain.BehavioralAlert{}
	now := time.Now()

	if event.RecordCount > 500 && event.Duration < time.Hour {
		alerts = append(alerts, domain.BehavioralAlert{
			AlertID:         uuid.New(),
			OfficerSnisidID: event.OfficerID,
			AlertType:       "MASS_DOWNLOAD",
			Description:     "Telechargement de plus de 500 dossiers en moins d une heure",
			RiskScore:       75,
			ModuleSource:    event.Module,
			AutoGenerated:   true,
			CreatedAt:       now,
		})
	}

	if event.Timestamp.Hour() >= 0 && event.Timestamp.Hour() < 5 {
		alerts = append(alerts, domain.BehavioralAlert{
			AlertID:         uuid.New(),
			OfficerSnisidID: event.OfficerID,
			AlertType:       "OFF_HOURS_ACCESS",
			Description:     "Acces au systeme entre 00h et 05h sans autorisation speciale",
			RiskScore:       60,
			ModuleSource:    event.Module,
			AutoGenerated:   true,
			CreatedAt:       now,
		})
	}

	if event.Action == "DELETE" && event.Module == "FIR-HT" {
		alerts = append(alerts, domain.BehavioralAlert{
			AlertID:         uuid.New(),
			OfficerSnisidID: event.OfficerID,
			AlertType:       "RECORD_DELETION",
			Description:     "Suppression d un dossier FIR-HT — verification requise",
			RiskScore:       95,
			ModuleSource:    "FIR-HT",
			AutoGenerated:   true,
			CreatedAt:       now,
		})
	}

	if event.Classification == "TOP_SECRET" && !event.IsAuthorized {
		alerts = append(alerts, domain.BehavioralAlert{
			AlertID:         uuid.New(),
			OfficerSnisidID: event.OfficerID,
			AlertType:       "SENSITIVE_RECORD_ACCESS",
			Description:     "Acces non autorise a un dossier TOP SECRET",
			RiskScore:       90,
			ModuleSource:    event.Module,
			AutoGenerated:   true,
			CreatedAt:       now,
		})
	}

	for _, alert := range alerts {
		s.alertRepo.Create(ctx, &alert)
		if alert.RiskScore >= 80 {
			s.igpnh.NotifyUrgent(ctx, alert)
		}
		s.kafka.Publish(ctx, "corr.behavioral.alert", alert)
	}
	return nil
}
