apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-verification-svc
  namespace: snisid-core
  labels:
    app: age-verification-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: age-verification-svc
  template:
    metadata:
      labels:
        app: age-verification-svc
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8095"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: age-verification-svc
        image: snisid/age-verification-svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8095
        env:
        - name: AGEVERIFY_DB_HOST
          valueFrom:
            secretKeyRef:
              name: snisid-db-credentials
              key: cockroach-host
        - name: AGEVERIFY_DB_PORT
          value: "26257"
        - name: AGEVERIFY_DB_NAME
          value: "snisid_ageverification"
        - name: AGEVERIFY_DB_USER
          valueFrom:
            secretKeyRef:
              name: snisid-db-credentials
              key: cockroach-user
        - name: AGEVERIFY_DB_SSLMODE
          value: "disable"
        - name: AGEVERIFY_KAFKA_BROKERS
          value: "kafka:9092"
        - name: AGEVERIFY_SERVICE_PORT
          value: "8095"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8095
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8095
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
