apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snisid-backend.fullname" . }}
  labels:
    {{- include "snisid-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snisid-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snisid-backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VAULT_ADDR
              value: {{ .Values.env.VAULT_ADDR | quote }}
          volumeMounts:
            - name: tmp-vol
              mountPath: /tmp
      volumes:
        - name: tmp-vol
          emptyDir: {}
