apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "snisid-backend.fullname" . }}
  labels:
    {{- include "snisid-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "snisid-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snisid-backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
  strategy:
    blueGreen:
      # Use the same service for active traffic
      activeService: {{ include "snisid-backend.fullname" . }}
      # Use a dedicated preview service for the new version
      previewService: {{ include "snisid-backend.fullname" . }}-preview
      autoPromotionEnabled: false # Mandatory approval gate required via ArgoCD UI/CLI before cutting over traffic
      scaleDownDelaySeconds: 30
