apiVersion: v1
kind: Service
metadata:
  name: cyber-ht
  namespace: snisid-core
  labels:
    app: cyber-ht
spec:
  type: ClusterIP
  ports:
  - port: 8210
    targetPort: 8210
    protocol: TCP
    name: http
  selector:
    app: cyber-ht
