apiVersion: v1
kind: Service
metadata:
  name: transport-security-ht
  namespace: snisid-national-security
  labels:
    app: transport-security-ht
spec:
  type: ClusterIP
  ports:
  - port: 8307
    targetPort: 8307
    protocol: TCP
    name: http
  selector:
    app: transport-security-ht
