apiVersion: v1
kind: Service
metadata:
  name: governance-svc
  namespace: snisid-core
  labels:
    app: governance-svc
spec:
  type: ClusterIP
  ports:
  - port: 8105
    targetPort: 8105
    protocol: TCP
    name: http
  selector:
    app: governance-svc
