apiVersion: v1
kind: Service
metadata:
  name: expl-svc
  namespace: snisid-core
  labels:
    app: expl-svc
spec:
  type: ClusterIP
  ports:
  - port: 8104
    targetPort: 8104
    protocol: TCP
    name: http
  selector:
    app: expl-svc