apiVersion: v1
kind: Service
metadata:
  name: counterintel-ht
  namespace: snisid-national-security
  labels:
    app: counterintel-ht
spec:
  type: ClusterIP
  ports:
  - port: 8310
    targetPort: 8310
    protocol: TCP
    name: http
  selector:
    app: counterintel-ht
