BEGIN;

CREATE TYPE mar_vessel_type AS ENUM (
    'CARGO_SHIP','TANKER','FISHING_BOAT','GO_FAST',
    'SAILBOAT','YACHT','FERRY','PATROL_BOAT',
    'WOODEN_BOAT','CANOE','UNKNOWN'
);

CREATE TYPE mar_vessel_status AS ENUM (
    'REGISTERED','STOLEN','SUSPECTED','DETAINED',
    'SUNK','DESTROYED','MISSING','INTERPOL_ALERT'
);

CREATE TYPE mar_incident_type AS ENUM (
    'DRUG_SEIZURE','ARMS_SEIZURE','MIGRANT_INTERDICTION',
    'SMUGGLING','SUSPICIOUS_ACTIVITY','DISTRESS',
    'PIRACY','ILLEGAL_FISHING','HUMAN_TRAFFICKING'
);

COMMIT;
