apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: snisid
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: nexus-policy
  namespace: snisid
spec:
  selector:
    matchLabels:
      app: nexus
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/snisid/sa/nexus-client"]
    to:
    - operation:
        methods: ["POST"]
        paths: ["/nexus.v1.NexusService/SubmitTask"]
