apiVersion: v1
kind: Service
metadata:
  name: sltd-svc
  namespace: snisid-core
  labels:
    app: sltd-svc
spec:
  type: ClusterIP
  ports:
  - port: 8108
    targetPort: 8108
    protocol: TCP
    name: http
  selector:
    app: sltd-svc