apiVersion: v1
kind: Service
metadata:
  name: iam-ht
  namespace: snisid-core
  labels:
    app: iam-ht
spec:
  type: ClusterIP
  ports:
  - port: 8207
    targetPort: 8207
    protocol: TCP
    name: http
  selector:
    app: iam-ht
