// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nexus.proto

package nexusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskPriority defines the urgency of a task.
type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_TASK_PRIORITY_LOW         TaskPriority = 1
	TaskPriority_TASK_PRIORITY_MEDIUM      TaskPriority = 2
	TaskPriority_TASK_PRIORITY_HIGH        TaskPriority = 3
	TaskPriority_TASK_PRIORITY_CRITICAL    TaskPriority = 4
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0: "TASK_PRIORITY_UNSPECIFIED",
		1: "TASK_PRIORITY_LOW",
		2: "TASK_PRIORITY_MEDIUM",
		3: "TASK_PRIORITY_HIGH",
		4: "TASK_PRIORITY_CRITICAL",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"TASK_PRIORITY_LOW":         1,
		"TASK_PRIORITY_MEDIUM":      2,
		"TASK_PRIORITY_HIGH":        3,
		"TASK_PRIORITY_CRITICAL":    4,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[0].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[0]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

// TaskStatus defines the lifecycle state of a task.
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 4
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 5
	TaskStatus_TASK_STATUS_RETRYING    TaskStatus = 6
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 7
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_QUEUED",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_RETRYING",
		7: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_QUEUED":      2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_COMPLETED":   4,
		"TASK_STATUS_FAILED":      5,
		"TASK_STATUS_RETRYING":    6,
		"TASK_STATUS_CANCELLED":   7,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{1}
}

// TaskDefinition defines a distributed task handled by the Nexus kernel.
type TaskDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,3,opt,name=priority,proto3,enum=nexus.v1.TaskPriority" json:"priority,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	mi := &file_nexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskDefinition) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *TaskDefinition) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskDefinition) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskDefinition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskDefinition) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TaskDefinition) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

// WorkflowState tracks the lifecycle of a complex multi-step orchestration.
type WorkflowState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId     string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CompletedSteps []string               `protobuf:"bytes,3,rep,name=completed_steps,json=completedSteps,proto3" json:"completed_steps,omitempty"`
	CurrentStep    string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	LastUpdated    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Context        map[string]string      `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkflowState) Reset() {
	*x = WorkflowState{}
	mi := &file_nexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowState) ProtoMessage() {}

func (x *WorkflowState) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowState.ProtoReflect.Descriptor instead.
func (*WorkflowState) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowState) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowState) GetCompletedSteps() []string {
	if x != nil {
		return x.CompletedSteps
	}
	return nil
}

func (x *WorkflowState) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *WorkflowState) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *WorkflowState) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// AgentSignal is a real-time message from a Kai execution agent.
type AgentSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=nexus.v1.TaskStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Result        *anypb.Any             `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSignal) Reset() {
	*x = AgentSignal{}
	mi := &file_nexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSignal) ProtoMessage() {}

func (x *AgentSignal) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSignal.ProtoReflect.Descriptor instead.
func (*AgentSignal) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{2}
}

func (x *AgentSignal) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSignal) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentSignal) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *AgentSignal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentSignal) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentSignal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// NexusCommand is a control message for the kernel.
type NexusCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusCommand) Reset() {
	*x = NexusCommand{}
	mi := &file_nexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusCommand) ProtoMessage() {}

func (x *NexusCommand) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusCommand.ProtoReflect.Descriptor instead.
func (*NexusCommand) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{3}
}

func (x *NexusCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *NexusCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *NexusCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *NexusCommand) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_nexus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_nexus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{5}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=nexus.v1.TaskStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_nexus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{6}
}

func (x *TaskStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskStatusUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRequest) Reset() {
	*x = WorkflowRequest{}
	mi := &file_nexus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRequest) ProtoMessage() {}

func (x *WorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRequest.ProtoReflect.Descriptor instead.
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

var File_nexus_proto protoreflect.FileDescriptor

const file_nexus_proto_rawDesc = "" +
	"\n" +
	"\vnexus.proto\x12\bnexus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\x94\x03\n" +
	"\x0eTaskDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x122\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x16.nexus.v1.TaskPriorityR\bpriority\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12B\n" +
	"\bmetadata\x18\x05 \x03(\v2&.nexus.v1.TaskDefinition.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x02\n" +
	"\rWorkflowState\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fcompleted_steps\x18\x03 \x03(\tR\x0ecompletedSteps\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12>\n" +
	"\acontext\x18\x06 \x03(\v2$.nexus.v1.WorkflowState.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\vAgentSignal\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.nexus.v1.TaskStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12,\n" +
	"\x06result\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x06result\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf6\x01\n" +
	"\fNexusCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12:\n" +
	"\x06params\x18\x03 \x03(\v2\".nexus.v1.NexusCommand.ParamsEntryR\x06params\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"&\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xaa\x01\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.nexus.v1.TaskStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"2\n" +
	"\x0fWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId*\x92\x01\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_PRIORITY_LOW\x10\x01\x12\x18\n" +
	"\x14TASK_PRIORITY_MEDIUM\x10\x02\x12\x16\n" +
	"\x12TASK_PRIORITY_HIGH\x10\x03\x12\x1a\n" +
	"\x16TASK_PRIORITY_CRITICAL\x10\x04*\xdb\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x18\n" +
	"\x14TASK_STATUS_RETRYING\x10\x06\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\a2\xa4\x02\n" +
	"\fNexusService\x12>\n" +
	"\n" +
	"SubmitTask\x12\x18.nexus.v1.TaskDefinition\x1a\x16.nexus.v1.TaskResponse\x12B\n" +
	"\rGetTaskStatus\x12\x15.nexus.v1.TaskRequest\x1a\x1a.nexus.v1.TaskStatusUpdate\x12G\n" +
	"\x12StreamAgentSignals\x12\x15.nexus.v1.AgentSignal\x1a\x16.nexus.v1.NexusCommand(\x010\x01\x12G\n" +
	"\x11GetWorkflowStatus\x12\x19.nexus.v1.WorkflowRequest\x1a\x17.nexus.v1.WorkflowStateB7Z5github.com/snisid/platform/api/proto/nexus/v1;nexusv1b\x06proto3"

var (
	file_nexus_proto_rawDescOnce sync.Once
	file_nexus_proto_rawDescData []byte
)

func file_nexus_proto_rawDescGZIP() []byte {
	file_nexus_proto_rawDescOnce.Do(func() {
		file_nexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)))
	})
	return file_nexus_proto_rawDescData
}

var file_nexus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nexus_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_nexus_proto_goTypes = []any{
	(TaskPriority)(0),             // 0: nexus.v1.TaskPriority
	(TaskStatus)(0),               // 1: nexus.v1.TaskStatus
	(*TaskDefinition)(nil),        // 2: nexus.v1.TaskDefinition
	(*WorkflowState)(nil),         // 3: nexus.v1.WorkflowState
	(*AgentSignal)(nil),           // 4: nexus.v1.AgentSignal
	(*NexusCommand)(nil),          // 5: nexus.v1.NexusCommand
	(*TaskResponse)(nil),          // 6: nexus.v1.TaskResponse
	(*TaskRequest)(nil),           // 7: nexus.v1.TaskRequest
	(*TaskStatusUpdate)(nil),      // 8: nexus.v1.TaskStatusUpdate
	(*WorkflowRequest)(nil),       // 9: nexus.v1.WorkflowRequest
	nil,                           // 10: nexus.v1.TaskDefinition.MetadataEntry
	nil,                           // 11: nexus.v1.WorkflowState.ContextEntry
	nil,                           // 12: nexus.v1.NexusCommand.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
	(*anypb.Any)(nil),             // 15: google.protobuf.Any
}
var file_nexus_proto_depIdxs = []int32{
	0,  // 0: nexus.v1.TaskDefinition.priority:type_name -> nexus.v1.TaskPriority
	10, // 1: nexus.v1.TaskDefinition.metadata:type_name -> nexus.v1.TaskDefinition.MetadataEntry
	13, // 2: nexus.v1.TaskDefinition.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: nexus.v1.TaskDefinition.timeout:type_name -> google.protobuf.Duration
	13, // 4: nexus.v1.WorkflowState.last_updated:type_name -> google.protobuf.Timestamp
	11, // 5: nexus.v1.WorkflowState.context:type_name -> nexus.v1.WorkflowState.ContextEntry
	1,  // 6: nexus.v1.AgentSignal.status:type_name -> nexus.v1.TaskStatus
	15, // 7: nexus.v1.AgentSignal.result:type_name -> google.protobuf.Any
	13, // 8: nexus.v1.AgentSignal.timestamp:type_name -> google.protobuf.Timestamp
	12, // 9: nexus.v1.NexusCommand.params:type_name -> nexus.v1.NexusCommand.ParamsEntry
	13, // 10: nexus.v1.NexusCommand.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 11: nexus.v1.TaskStatusUpdate.status:type_name -> nexus.v1.TaskStatus
	13, // 12: nexus.v1.TaskStatusUpdate.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 13: nexus.v1.NexusService.SubmitTask:input_type -> nexus.v1.TaskDefinition
	7,  // 14: nexus.v1.NexusService.GetTaskStatus:input_type -> nexus.v1.TaskRequest
	4,  // 15: nexus.v1.NexusService.StreamAgentSignals:input_type -> nexus.v1.AgentSignal
	9,  // 16: nexus.v1.NexusService.GetWorkflowStatus:input_type -> nexus.v1.WorkflowRequest
	6,  // 17: nexus.v1.NexusService.SubmitTask:output_type -> nexus.v1.TaskResponse
	8,  // 18: nexus.v1.NexusService.GetTaskStatus:output_type -> nexus.v1.TaskStatusUpdate
	5,  // 19: nexus.v1.NexusService.StreamAgentSignals:output_type -> nexus.v1.NexusCommand
	3,  // 20: nexus.v1.NexusService.GetWorkflowStatus:output_type -> nexus.v1.WorkflowState
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_nexus_proto_init() }
func file_nexus_proto_init() {
	if File_nexus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_proto_goTypes,
		DependencyIndexes: file_nexus_proto_depIdxs,
		EnumInfos:         file_nexus_proto_enumTypes,
		MessageInfos:      file_nexus_proto_msgTypes,
	}.Build()
	File_nexus_proto = out.File
	file_nexus_proto_goTypes = nil
	file_nexus_proto_depIdxs = nil
}
