apiVersion: v1
kind: Service
metadata:
  name: trafar-svc
  namespace: snisid-core
  labels:
    app: trafar-svc
spec:
  type: ClusterIP
  ports:
  - port: 8105
    targetPort: 8105
    protocol: TCP
    name: http
  selector:
    app: trafar-svc