apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/part-of: snisid
spec:
  provider:
    vault:
      server: http://vault-internal:8200
      path: kv-v2
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: snisid-service
          serviceAccountRef:
            name: snisid-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snisid-postgres-secret
  namespace: snisid
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: snisid-postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: shared/postgres
      property: password
  - secretKey: host
    remoteRef:
      key: shared/postgres
      property: host
  - secretKey: dbname
    remoteRef:
      key: shared/postgres
      property: dbname
  - secretKey: username
    remoteRef:
      key: shared/postgres
      property: user
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snisid-jwt-secret
  namespace: snisid
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: snisid-jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: shared/jwt
      property: secret
  - secretKey: jwt-ttl
    remoteRef:
      key: shared/jwt
      property: ttl
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snisid-neo4j-secret
  namespace: snisid
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: snisid-neo4j-secret
    creationPolicy: Owner
  data:
  - secretKey: neo4j-password
    remoteRef:
      key: shared/neo4j
      property: password
  - secretKey: neo4j-host
    remoteRef:
      key: shared/neo4j
      property: host
