apiVersion: v1
kind: ResourceQuota
metadata:
  name: snisid-compute-resources
  namespace: snisid
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: snisid-limit-range
  namespace: snisid
spec:
  limits:
    - default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 512Mi
      type: Container
