apiVersion: v1
kind: Service
metadata:
  name: id-core
  namespace: snisid-core
  labels:
    app: id-core
spec:
  type: ClusterIP
  ports:
  - port: 8201
    targetPort: 8201
    protocol: TCP
    name: http
  selector:
    app: id-core
