apiVersion: v1
kind: Service
metadata:
  name: field-ht
  namespace: snisid-core
  labels:
    app: field-ht
spec:
  type: ClusterIP
  ports:
  - port: 8212
    targetPort: 8212
    protocol: TCP
    name: http
  selector:
    app: field-ht
