---
# Default Deny-All Ingress and Egress for snisid-core
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: snisid-core
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Allow core components to reach DNS
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: snisid-core
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
# Default Deny-All for snisid-data
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: snisid-data
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Allow snisid-core to access snisid-data (Postgres)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-core-to-db
  namespace: snisid-data
spec:
  podSelector:
    matchLabels:
      app: snisid-database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: snisid-core
      podSelector:
        matchLabels:
          app: snisid-backend
    ports:
    - protocol: TCP
      port: 5432
