CREATE TABLE per_wanted_persons (
    record_id       UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    record_number   VARCHAR(50) UNIQUE NOT NULL,
    niu             VARCHAR(20),
    last_name       VARCHAR(100),
    first_name      VARCHAR(100),
    aliases         JSONB DEFAULT '[]',
    date_of_birth   DATE,
    gender          CHAR(1),
    nationality     CHAR(3),
    warrant_type    VARCHAR(50) NOT NULL,
    warrant_number  VARCHAR(100),
    issuing_court   VARCHAR(200),
    issuing_date    DATE NOT NULL,
    charges         JSONB NOT NULL DEFAULT '[]',
    danger_level    VARCHAR(10) DEFAULT 'MEDIUM' CHECK (danger_level IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    armed_dangerous BOOLEAN DEFAULT FALSE,
    height_cm       SMALLINT,
    weight_kg       SMALLINT,
    eye_color       VARCHAR(30),
    hair_color      VARCHAR(30),
    distinguishing_marks TEXT,
    entering_agency VARCHAR(100) NOT NULL,
    entering_officer VARCHAR(100) NOT NULL,
    mco_contact     VARCHAR(200),
    last_known_location VARCHAR(200),
    status          VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','CLEARED','EXPIRED','SUSPENDED')),
    expiry_date     DATE,
    fingerprint_ref UUID,
    photo_refs      JSONB DEFAULT '[]',
    bio_sample_ref  UUID REFERENCES bio_str_profiles(sample_id),
    interpol_notice VARCHAR(50),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    last_hit_at     TIMESTAMPTZ
);

CREATE INDEX idx_per_wanted_niu ON per_wanted_persons(niu);
CREATE INDEX idx_per_wanted_status ON per_wanted_persons(status);
CREATE INDEX idx_per_wanted_name ON per_wanted_persons USING gin(to_tsvector('french', COALESCE(last_name,'') || ' ' || COALESCE(first_name,'')));

CREATE TABLE per_missing_persons (
    record_id       UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    record_number   VARCHAR(50) UNIQUE NOT NULL,
    niu             VARCHAR(20),
    last_name       VARCHAR(100) NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    date_of_birth   DATE,
    age_at_missing  SMALLINT,
    gender          CHAR(1),
    nationality     CHAR(3),
    category        VARCHAR(20) NOT NULL CHECK (category IN ('CHILD','ENDANGERED','INVOLUNTARY','CATASTROPHE','UNEMANCIPATED','OTHER')),
    missing_date    TIMESTAMPTZ NOT NULL,
    missing_location VARCHAR(200) NOT NULL,
    circumstances   TEXT,
    last_seen_clothing VARCHAR(500),
    height_cm       SMALLINT,
    weight_kg       SMALLINT,
    distinctive_features TEXT,
    family_contact  VARCHAR(200),
    family_phone    VARCHAR(50),
    photo_refs      JSONB DEFAULT '[]',
    bio_sample_ref  UUID REFERENCES bio_str_profiles(sample_id),
    family_bio_refs JSONB DEFAULT '[]',
    medical_conditions TEXT,
    medications     TEXT,
    status          VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','LOCATED','DECEASED','CANCELLED')),
    located_date    TIMESTAMPTZ,
    entering_agency VARCHAR(100) NOT NULL,
    ncmec_notified  BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE per_sex_offenders (
    record_id       UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    niu             VARCHAR(20) NOT NULL,
    conviction_date DATE NOT NULL,
    conviction_court VARCHAR(200) NOT NULL,
    offenses        JSONB NOT NULL DEFAULT '[]',
    risk_level      VARCHAR(10) CHECK (risk_level IN ('LOW','MEDIUM','HIGH')),
    registration_expiry DATE,
    current_address TEXT,
    employer        VARCHAR(200),
    restrictions    TEXT,
    last_verified   DATE,
    status          VARCHAR(20) DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE per_gang_members (
    record_id       UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    niu             VARCHAR(20),
    last_name       VARCHAR(100),
    first_name      VARCHAR(100),
    aliases         JSONB DEFAULT '[]',
    gang_name       VARCHAR(200) NOT NULL,
    gang_code       VARCHAR(50),
    membership_type VARCHAR(30) CHECK (membership_type IN ('LEADER','MEMBER','ASSOCIATE','PROSPECT')),
    territory       VARCHAR(200),
    known_weapons   JSONB DEFAULT '[]',
    criminal_activities JSONB DEFAULT '[]',
    threat_level    VARCHAR(10) DEFAULT 'HIGH' CHECK (threat_level IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    intelligence_notes TEXT,
    source_reliability VARCHAR(10),
    status          VARCHAR(20) DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);
