apiVersion: v1
kind: Service
metadata:
  name: sigeo-svc
  namespace: snisid-core
  labels:
    app: sigeo-svc
spec:
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: 8125
    protocol: TCP
    name: http
  selector:
    app: sigeo-svc