apiVersion: v1
kind: Service
metadata:
  name: port-svc
  namespace: snisid-core
  labels:
    app: port-svc
spec:
  type: ClusterIP
  ports:
  - port: 8111
    targetPort: 8111
    protocol: TCP
    name: http
  selector:
    app: port-svc