BEGIN;

CREATE TYPE blkl_restriction_type AS ENUM (
    'ENTRY_BAN',
    'EXIT_BAN',
    'BOTH_BAN',
    'CONDITIONAL_BAN'
);

CREATE TYPE blkl_source AS ENUM (
    'JUDICIAL_ORDER', 'WANTED_WARRANT', 'UN_SANCTIONS',
    'OFAC_SANCTIONS', 'MINISTERIAL_ORDER', 'EXPULSION',
    'OPR_TRAVEL_RESTRICTION', 'INTERPOL_NOTICE'
);

COMMIT;
