apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdl-svc
  namespace: snisid-core
  labels:
    app: mdl-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mdl-svc
  template:
    metadata:
      labels:
        app: mdl-svc
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8094"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: mdl-svc
        image: snisid/mdl-svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8094
        env:
        - name: MDL_DB_HOST
          valueFrom:
            secretKeyRef:
              name: snisid-db-credentials
              key: cockroach-host
        - name: MDL_DB_PORT
          value: "26257"
        - name: MDL_DB_NAME
          value: "snisid_mdl"
        - name: MDL_DB_USER
          valueFrom:
            secretKeyRef:
              name: snisid-db-credentials
              key: cockroach-user
        - name: MDL_DB_SSLMODE
          value: "disable"
        - name: MDL_KAFKA_BROKERS
          value: "kafka:9092"
        - name: MDL_SERVICE_PORT
          value: "8094"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8094
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8094
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
