apiVersion: v1
kind: Service
metadata:
  name: employee-verify-svc
  namespace: snisid-core
  labels:
    app: employee-verify-svc
spec:
  type: ClusterIP
  ports:
  - port: 8096
    targetPort: 8096
    protocol: TCP
    name: http
  selector:
    app: employee-verify-svc
