package domain

import (
	"time"

	"github.com/google/uuid"
)

type AllegationType string

const (
	DataLeakToGang      AllegationType = "DATA_LEAK_TO_GANG"
	RecordTampering     AllegationType = "RECORD_TAMPERING"
	UnauthorizedAccess  AllegationType = "UNAUTHORIZED_ACCESS"
	Bribery             AllegationType = "BRIBERY"
	ExtortionOfCivilians AllegationType = "EXTORTION_OF_CIVILIANS"
	FacilitatedPrisonEscape AllegationType = "FACILITATED_PRISON_ESCAPE"
	StolenCredentials   AllegationType = "STOLEN_CREDENTIALS"
	FinancialCorruption AllegationType = "FINANCIAL_CORRUPTION"
	GangAffiliation     AllegationType = "GANG_AFFILIATION"
	OtherAllegation     AllegationType = "OTHER"
)

type Severity string

const (
	SevLow      Severity = "LOW"
	SevMedium   Severity = "MEDIUM"
	SevHigh     Severity = "HIGH"
	SevCritical Severity = "CRITICAL"
)

type CaseStatus string

const (
	Reported         CaseStatus = "REPORTED"
	UnderInvestigation CaseStatus = "UNDER_INVESTIGATION"
	Substantiated    CaseStatus = "SUBSTANTIATED"
	Unsubstantiated  CaseStatus = "UNSUBSTANTIATED"
	ReferredToParquet CaseStatus = "REFERRED_TO_PARQUET"
	Closed           CaseStatus = "CLOSED"
)

type IntegrityCase struct {
	ID                 uuid.UUID      `json:"case_id" db:"case_id"`
	NationalCorrID     string         `json:"national_corr_id" db:"national_corr_id"`
	OfficerSNISIDID    uuid.UUID      `json:"officer_snisid_id" db:"officer_snisid_id"`
	OfficerBadge       *string        `json:"officer_badge,omitempty" db:"officer_badge"`
	OfficerUnit        *string        `json:"officer_unit,omitempty" db:"officer_unit"`
	OfficerRank        *string        `json:"officer_rank,omitempty" db:"officer_rank"`
	AllegationType     AllegationType `json:"allegation_type" db:"allegation_type"`
	Severity           Severity       `json:"severity" db:"severity"`
	Status             CaseStatus     `json:"status" db:"status"`
	AllegationSummary  string         `json:"allegation_summary" db:"allegation_summary"`
	IncidentDateFrom   *time.Time     `json:"incident_date_from,omitempty" db:"incident_date_from"`
	IncidentDateTo     *time.Time     `json:"incident_date_to,omitempty" db:"incident_date_to"`
	GangID             *uuid.UUID     `json:"gang_id,omitempty" db:"gang_id"`
	FinancialGainUSD   *float64       `json:"financial_gain_usd,omitempty" db:"financial_gain_usd"`
	ReportedByType     *string        `json:"reported_by_type,omitempty" db:"reported_by_type"`
	ReportingDate      time.Time      `json:"reporting_date" db:"reporting_date"`
	IsWhistleblower    *bool          `json:"is_whistleblower,omitempty" db:"is_whistleblower"`
	InvestigationStart *time.Time     `json:"investigation_start,omitempty" db:"investigation_start"`
	CreatedBy          uuid.UUID      `json:"created_by" db:"created_by"`
	CreatedAt          time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at" db:"updated_at"`
}

type WhistleblowerReport struct {
	ID                uuid.UUID     `json:"report_id" db:"report_id"`
	ReportToken       string        `json:"report_token" db:"report_token"`
	AllegationType    AllegationType `json:"allegation_type" db:"allegation_type"`
	SeverityEstimate  *Severity     `json:"severity_estimate,omitempty" db:"severity_estimate"`
	Description       string        `json:"description" db:"description"`
	SubmissionDate    time.Time     `json:"submission_date" db:"submission_date"`
	Processed         *bool         `json:"processed,omitempty" db:"processed"`
	IntegrityCaseID   *uuid.UUID    `json:"integrity_case_id,omitempty" db:"integrity_case_id"`
	CreatedAt         time.Time     `json:"created_at" db:"created_at"`
}

type BehavioralAlert struct {
	ID              uuid.UUID `json:"alert_id" db:"alert_id"`
	OfficerSNISIDID uuid.UUID `json:"officer_snisid_id" db:"officer_snisid_id"`
	AlertType       string    `json:"alert_type" db:"alert_type"`
	Description     string    `json:"description" db:"description"`
	ModuleSource    *string   `json:"module_source,omitempty" db:"module_source"`
	RiskScore       *int      `json:"risk_score,omitempty" db:"risk_score"`
	AutoGenerated   *bool     `json:"auto_generated,omitempty" db:"auto_generated"`
	Reviewed        *bool     `json:"reviewed,omitempty" db:"reviewed"`
	IsFalsePositive *bool     `json:"is_false_positive,omitempty" db:"is_false_positive"`
	CreatedAt       time.Time `json:"created_at" db:"created_at"`
}

type AssetDeclaration struct {
	ID                uuid.UUID `json:"declaration_id" db:"declaration_id"`
	OfficerSNISIDID   uuid.UUID `json:"officer_snisid_id" db:"officer_snisid_id"`
	DeclarationYear   *int      `json:"declaration_year,omitempty" db:"declaration_year"`
	RealEstateUSD     *float64  `json:"real_estate_usd,omitempty" db:"real_estate_usd"`
	VehiclesUSD       *float64  `json:"vehicles_usd,omitempty" db:"vehicles_usd"`
	BankAccountsUSD   *float64  `json:"bank_accounts_usd,omitempty" db:"bank_accounts_usd"`
	OtherAssetsUSD    *float64  `json:"other_assets_usd,omitempty" db:"other_assets_usd"`
	IsFlagged         *bool     `json:"is_flagged,omitempty" db:"is_flagged"`
	CreatedAt         time.Time `json:"created_at" db:"created_at"`
}

type OpenCaseRequest struct {
	OfficerSNISIDID string  `json:"officer_snisid_id" binding:"required"`
	AllegationType  string  `json:"allegation_type" binding:"required"`
	Severity        string  `json:"severity" binding:"required"`
	AllegationSummary string `json:"allegation_summary" binding:"required"`
	GangID          string  `json:"gang_id"`
}

type SubmitWhistleblowerRequest struct {
	AllegationType   string `json:"allegation_type" binding:"required"`
	SeverityEstimate string `json:"severity_estimate"`
	Description      string `json:"description" binding:"required"`
}

type SubmitDeclarationRequest struct {
	OfficerSNISIDID string  `json:"officer_snisid_id" binding:"required"`
	DeclarationYear int     `json:"declaration_year" binding:"required"`
	RealEstateUSD   float64 `json:"real_estate_usd"`
	VehiclesUSD     float64 `json:"vehicles_usd"`
	BankAccountsUSD float64 `json:"bank_accounts_usd"`
	OtherAssetsUSD  float64 `json:"other_assets_usd"`
}

type IntegrityRepository interface {
	CreateCase(c *IntegrityCase) (*IntegrityCase, error)
	FindByID(id uuid.UUID) (*IntegrityCase, error)
	FindActive() ([]IntegrityCase, error)
	CreateWhistleblowerReport(wr *WhistleblowerReport) (*WhistleblowerReport, error)
	FindByToken(token string) (*WhistleblowerReport, error)
	FindBehavioralAlerts() ([]BehavioralAlert, error)
	CreateAssetDeclaration(ad *AssetDeclaration) (*AssetDeclaration, error)
	FindFlaggedDeclarations() ([]AssetDeclaration, error)
}
