import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerVerifyIdentityTool } from './identity/verifyIdentity.js';
import { registerCitizenProfileTool } from './identity/citizenProfile.js';
import { registerBiometricMatchTool } from './identity/biometricMatch.js';
import { registerBirthCertificateTool } from './identity/birthCertificate.js';
import { registerPassportLookupTool } from './identity/passportLookup.js';
import { registerNationalityCheckTool } from './identity/nationalityCheck.js';
import { registerFaceVerificationTool } from './identity/faceVerification.js';
import { registerIdentityRiskTool } from './identity/identityRisk.js';
import { registerCriminalRecordTool } from './justice/criminalRecord.js';
import { registerWarrantLookupTool } from './justice/warrantLookup.js';
import { registerCourtCasesTool } from './justice/courtCases.js';
import { registerDetentionStatusTool } from './justice/detentionStatus.js';
import { registerJudicialHistoryTool } from './justice/judicialHistory.js';
import { registerWantedPersonTool } from './police/wantedPerson.js';
import { registerIncidentLookupTool } from './police/incidentLookup.js';
import { registerGangAffiliationTool } from './police/gangAffiliation.js';
import { registerWeaponPermitTool } from './police/weaponPermit.js';
import { registerThreatMonitoringTool } from './police/threatMonitoring.js';
import { registerBorderAlertsTool } from './immigration/borderAlerts.js';
import { registerTravelHistoryTool } from './immigration/travelHistory.js';
import { registerVisaLookupTool } from './immigration/visaLookup.js';
import { registerEntryExitTool } from './immigration/entryExit.js';
import { registerWatchlistScanTool } from './immigration/watchlistScan.js';
import { registerStudentVerificationTool } from './education/studentVerification.js';
import { registerDiplomaVerificationTool } from './education/diplomaVerification.js';
import { registerInstitutionLookupTool } from './education/institutionLookup.js';
import { registerAcademicHistoryTool } from './education/academicHistory.js';
import { registerVerifyNifTool } from './tax/verifyNIF.js';
import { registerTaxComplianceTool } from './tax/taxCompliance.js';
import { registerBusinessRegistryTool } from './tax/businessRegistry.js';
import { registerFinancialRiskTool } from './tax/financialRisk.js';
import { registerFusionAnalysisTool } from './intelligence/fusionAnalysis.js';
import { registerRiskScoreTool } from './intelligence/riskScore.js';
import { registerNetworkAnalysisTool } from './intelligence/networkAnalysis.js';
import { registerThreatDetectionTool } from './intelligence/threatDetection.js';
import { registerBehaviorAnalysisTool } from './intelligence/behaviorAnalysis.js';

export function registerAllTools(server: McpServer): void {
  registerVerifyIdentityTool(server);
  registerCitizenProfileTool(server);
  registerBiometricMatchTool(server);
  registerBirthCertificateTool(server);
  registerPassportLookupTool(server);
  registerNationalityCheckTool(server);
  registerFaceVerificationTool(server);
  registerIdentityRiskTool(server);
  registerCriminalRecordTool(server);
  registerWarrantLookupTool(server);
  registerCourtCasesTool(server);
  registerDetentionStatusTool(server);
  registerJudicialHistoryTool(server);
  registerWantedPersonTool(server);
  registerIncidentLookupTool(server);
  registerGangAffiliationTool(server);
  registerWeaponPermitTool(server);
  registerThreatMonitoringTool(server);
  registerBorderAlertsTool(server);
  registerTravelHistoryTool(server);
  registerVisaLookupTool(server);
  registerEntryExitTool(server);
  registerWatchlistScanTool(server);
  registerStudentVerificationTool(server);
  registerDiplomaVerificationTool(server);
  registerInstitutionLookupTool(server);
  registerAcademicHistoryTool(server);
  registerVerifyNifTool(server);
  registerTaxComplianceTool(server);
  registerBusinessRegistryTool(server);
  registerFinancialRiskTool(server);
  registerFusionAnalysisTool(server);
  registerRiskScoreTool(server);
  registerNetworkAnalysisTool(server);
  registerThreatDetectionTool(server);
  registerBehaviorAnalysisTool(server);
}
