apiVersion: v1
kind: Service
metadata:
  name: card-ht
  namespace: snisid-core
  labels:
    app: card-ht
spec:
  type: ClusterIP
  ports:
  - port: 8204
    targetPort: 8204
    protocol: TCP
    name: http
  selector:
    app: card-ht
