BEGIN;

CREATE TYPE corr_allegation_type AS ENUM (
    'DATA_LEAK_TO_GANG',
    'RECORD_TAMPERING',
    'UNAUTHORIZED_ACCESS',
    'BRIBERY',
    'EXTORTION_OF_CIVILIANS',
    'FACILITATED_PRISON_ESCAPE',
    'STOLEN_CREDENTIALS',
    'FINANCIAL_CORRUPTION',
    'GANG_AFFILIATION',
    'OTHER'
);

CREATE TYPE corr_severity AS ENUM (
    'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
);

CREATE TYPE corr_status AS ENUM (
    'REPORTED', 'UNDER_INVESTIGATION', 'SUBSTANTIATED',
    'UNSUBSTANTIATED', 'REFERRED_TO_PARQUET', 'CLOSED'
);

COMMIT;
