apiVersion: v1
kind: Service
metadata:
  name: humint-ht
  namespace: snisid-national-security
  labels:
    app: humint-ht
spec:
  type: ClusterIP
  ports:
  - port: 8302
    targetPort: 8302
    protocol: TCP
    name: http
  selector:
    app: humint-ht
