apiVersion: v1
kind: Service
metadata:
  name: sipep-svc
  namespace: snisid-core
  labels:
    app: sipep-svc
spec:
  type: ClusterIP
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    name: http
  selector:
    app: sipep-svc