apiVersion: v1
kind: Service
metadata:
  name: vict-svc
  namespace: snisid-core
  labels:
    app: vict-svc
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  selector:
    app: vict-svc