apiVersion: v1
kind: Service
metadata:
  name: blkl-svc
  namespace: snisid-core
  labels:
    app: blkl-svc
spec:
  type: ClusterIP
  ports:
  - port: 8110
    targetPort: 8110
    protocol: TCP
    name: http
  selector:
    app: blkl-svc