apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snisid
resources:
- namespaces.yaml
- network-policies.yaml
- resource-quotas.yaml
commonLabels:
  app.kubernetes.io/part-of: snisid
  app.kubernetes.io/managed-by: kustomize
