apiVersion: v1
kind: Namespace
metadata:
  name: snisid
  labels:
    app.kubernetes.io/part-of: snisid
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: snisid-apps
  labels:
    app.kubernetes.io/part-of: snisid
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: snisid-observability
  labels:
    app.kubernetes.io/part-of: snisid
