import { PERMISSIONS, type Permission } from './permissions.js';

export const ROLES = {
  SNISID_ADMIN: 'SNISID_ADMIN',
  ONI_AGENT: 'ONI_AGENT',
  PNH_INVESTIGATOR: 'PNH_INVESTIGATOR',
  MJSP_MAGISTRATE: 'MJSP_MAGISTRATE',
  IMMIGRATION_OFFICER: 'IMMIGRATION_OFFICER',
  TAX_OFFICER: 'TAX_OFFICER',
  EDUCATION_OFFICER: 'EDUCATION_OFFICER',
  INTELLIGENCE_ANALYST: 'INTELLIGENCE_ANALYST',
  AUDITOR: 'AUDITOR',
  SOC_ANALYST: 'SOC_ANALYST',
  AI_AGENT: 'AI_AGENT'
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SNISID_ADMIN: Object.values(PERMISSIONS),
  ONI_AGENT: [PERMISSIONS.IDENTITY_VERIFY, PERMISSIONS.IDENTITY_READ, PERMISSIONS.IDENTITY_BIOMETRIC],
  PNH_INVESTIGATOR: [PERMISSIONS.IDENTITY_VERIFY, PERMISSIONS.POLICE_READ, PERMISSIONS.POLICE_THREAT, PERMISSIONS.JUSTICE_READ],
  MJSP_MAGISTRATE: [PERMISSIONS.IDENTITY_VERIFY, PERMISSIONS.JUSTICE_READ],
  IMMIGRATION_OFFICER: [PERMISSIONS.IDENTITY_VERIFY, PERMISSIONS.IMMIGRATION_READ],
  TAX_OFFICER: [PERMISSIONS.IDENTITY_VERIFY, PERMISSIONS.TAX_READ, PERMISSIONS.TAX_RISK],
  EDUCATION_OFFICER: [PERMISSIONS.IDENTITY_VERIFY, PERMISSIONS.EDUCATION_READ],
  INTELLIGENCE_ANALYST: [PERMISSIONS.IDENTITY_VERIFY, PERMISSIONS.INTELLIGENCE_READ, PERMISSIONS.INTELLIGENCE_ANALYZE],
  AUDITOR: [PERMISSIONS.AUDIT_READ],
  SOC_ANALYST: [PERMISSIONS.AUDIT_READ, PERMISSIONS.SECURITY_ADMIN],
  AI_AGENT: [PERMISSIONS.IDENTITY_VERIFY]
};
