apiVersion: v1
kind: Service
metadata:
  name: critical-infra-protection-ht
  namespace: snisid-national-security
  labels:
    app: critical-infra-protection-ht
spec:
  type: ClusterIP
  ports:
  - port: 8311
    targetPort: 8311
    protocol: TCP
    name: http
  selector:
    app: critical-infra-protection-ht
