apiVersion: apps/v1
kind: Deployment
metadata:
  name: afis-svc
  namespace: snisid-core
  labels:
    app: afis-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: afis-svc
  template:
    metadata:
      labels:
        app: afis-svc
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8091"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: afis-svc
        image: snisid/afis-svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        env:
        - name: PORT
          value: "8091"
        - name: ENV
          value: "prod"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: snisid-db-credentials
              key: postgres-url
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8091
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8091
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"