apiVersion: v1
kind: Service
metadata:
  name: afis-svc
  namespace: snisid-core
  labels:
    app: afis-svc
spec:
  type: ClusterIP
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: http
  selector:
    app: afis-svc